<a href="https://colab.research.google.com/github/armandossrecife/teste/blob/main/solucao_sistemas_lineares.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Usando a regra de Cramer para resolver sistemas lineares

https://pt.wikipedia.org/wiki/Regra_de_Cramer

In [39]:
import numpy as np

# Solução de sistemas lineares usando a regra de Cramer
# Sistema de equações com duas incognitas:
# 2x + y = 5
# x + 2y = 4

# 2 1 5
# 1 2 4

# matriz A
A = np.array([[2, 1], [1, 2]])
print("Matriz A: ", A)

# matriz b
b = np.array([5, 4])
print("Matriz b", b)

# Calcula o determinante de A
det_A = np.linalg.det(A)

if det_A == 0:
    print("O sistema não tem solução única.")
else:
    print("O sistema tem uma solução única.")

# Criar novas matrizes substituindo as colunas da matriz de coeficientes
# pelo vetor de termos independentes
A1 = np.array([[5, 1], [4, 2]])
A2 = np.array([[2, 5], [1, 4]])

# Calcula os determinantes das novas matrizes A1 e A2
det_A1 = np.linalg.det(A1)
det_A2 = np.linalg.det(A2)

# Calcula os valores das incognitas
x = det_A1 / det_A
y = det_A2 / det_A

print("x =", round(x, 2))
print("y =", round(y, 2))

Matriz A:  [[2 1]
 [1 2]]
Matriz b [5 4]
O sistema tem uma solução única.
x = 2.0
y = 1.0


In [40]:
# Sistema de equações:
# 2x + y - z = 3
# x - 3y + 2z = -7
# 4x + y + z = 6

# Criando a matriz de coeficientes e o vetor de termos independentes
A = np.array([[2, 1, -1],
              [1, -3, 2],
              [4, 1, 1]])
print("Matriz A: ", A)

b = np.array([3, -7, 6])
print("Matriz b: ", b)

# Calculando o determinante da matriz de coeficientes
det_A = np.linalg.det(A)

if det_A == 0:
    print("O sistema não tem solução única.")
else:
    print("O sistema tem uma solução única.")

# Criando novas matrizes substituindo as colunas da matriz de coeficientes pelo vetor b
A1 = np.array([[3, 1, -1],
              [-7, -3, 2],
              [6, 1, 1]])
A2 = np.array([[2, 3, -1],
              [1, -7, 2],
              [4, 6, 1]])
A3 = np.array([[2, 1, 3],
              [1, -3, -7],
              [4, 1, 6]])

# Calculando os determinantes das novas matrizes
det_A1 = np.linalg.det(A1)
det_A2 = np.linalg.det(A2)
det_A3 = np.linalg.det(A3)

# Calculando as incógnitas
x = det_A1 / det_A
y = det_A2 / det_A
z = det_A3 / det_A

print("x =", round(x, 3))
print("y =", round(y, 3))
print("z =", round(z, 3))

Matriz A:  [[ 2  1 -1]
 [ 1 -3  2]
 [ 4  1  1]]
Matriz b:  [ 3 -7  6]
O sistema tem uma solução única.
x = 0.437
y = 3.188
z = 1.063


**Explicação:**

1. **Definição do sistema:** Definimos um sistema linear com três equações e três incógnitas.
2. **Criação das matrizes:** Criamos a matriz de coeficientes `A` e o vetor de termos independentes `b`.
3. **Cálculo do determinante:** Calculamos o determinante da matriz `A` usando `np.linalg.det`.
4. **Novas matrizes:** Criamos novas matrizes `A1`, `A2` e `A3` substituindo as colunas de `A` por `b`.
5. **Determinantes das novas matrizes:** Calculamos os determinantes das novas matrizes.
6. **Cálculo das incógnitas:** Aplicamos a regra de Cramer para encontrar os valores de `x`, `y` e `z`.

**Importante:**

* **Eficiência:** Embora a regra de Cramer seja útil para entender o conceito, ela não é eficiente para sistemas grandes. Para sistemas maiores, métodos como eliminação de Gauss ou decomposição LU são mais adequados.
* **Singularidade:** Se o determinante da matriz de coeficientes for zero, o sistema não possui solução única ou possui infinitas soluções.
* **NumPy:** A biblioteca NumPy oferece funções mais eficientes para resolver sistemas lineares, como `np.linalg.solve`.

**Considerações Adicionais:**

* **Função:** Você pode criar uma função para resolver sistemas lineares usando a regra de Cramer, tornando o código mais reutilizável.
* **Verificação:** Sempre verifique se o determinante da matriz de coeficientes é diferente de zero antes de aplicar a regra de Cramer.
* **Sistemas maiores:** Para sistemas maiores, considere utilizar bibliotecas especializadas em álgebra linear, como SciPy.

**Conclusão:**

Este exemplo demonstra como utilizar a regra de Cramer em Python para resolver sistemas lineares de 3x3. Embora a regra de Cramer tenha limitações em termos de eficiência, ela é uma ferramenta útil para entender os conceitos por trás da resolução de sistemas lineares.

# Usando o solve da biblioteca numpy para resolver sistemas lineares

https://numpy.org/doc/2.0/reference/generated/numpy.linalg.solve.html

Resolva uma equação matricial linear ou um sistema de equações escalares lineares.

In [41]:
# Sistema de equações com duas incognitas:
# 2x + y = 5
# x + 2y = 4

# matriz A
A = np.array([[2, 1], [1, 2]])
print("Matriz A: ", A)

# matriz b
b = np.array([5, 4])
print("Matriz b", b)

# Resolvendo o sistema
x = np.linalg.solve(A, b)
print("Solução: ")
print("x: ",x)

Matriz A:  [[2 1]
 [1 2]]
Matriz b [5 4]
Solução: 
x:  [2. 1.]


In [42]:
print("2x + y = 5")
print("x + 2y = 4")
print("Solução: ")
print("x:", x[0])
print("y:", x[1])

2x + y = 5
x + 2y = 4
Solução: 
x: 2.0
y: 1.0


In [43]:
# Sistema de equações com três incognitas:
# 2x + y - z = 3
# x - 3y + 2z = -7
# 4x + y + z = 6

# Criando a matriz de coeficientes
A = np.array([[2, 1, -1],
              [1, -3, 2],
              [4, 1, 1]])
print("Matriz de coefientes: ", A)

# vetor de termos independentes
b = np.array([3, -7, 6])
print("Matriz de termos independentes: ", b)

# Resolvendo o sistema
x = np.linalg.solve(A, b)
print("Solução: ")
print("x =", x)

Matriz de coefientes:  [[ 2  1 -1]
 [ 1 -3  2]
 [ 4  1  1]]
Matriz de termos independentes:  [ 3 -7  6]
Solução: 
x = [0.4375 3.1875 1.0625]


In [44]:
print("2x + y - z = 3")
print("x - 3y + 2z = -7")
print("4x + y + z = 6")
print("Solução: ")
print("x:", x[0])
print("y:", x[1])
print("z:", x[2])

2x + y - z = 3
x - 3y + 2z = -7
4x + y + z = 6
Solução: 
x: 0.4375
y: 3.1875
z: 1.0625


In [45]:
# Sistema de equações com quatro incógnitas:
# 2x + y - z + w = 3
# x - 3y + 2z - w = -7
# 4x + y + z + 2w = 6
# 3x - 2y + z - w = 1

# Criando a matriz de coeficientes e o vetor de termos independentes
A = np.array([[2, 1, -1, 1],
              [1, -3, 2, -1],
              [4, 1, 1, 2],
              [3, -2, 1, -1]])
print("Matriz de coeficientes: ", A)

b = np.array([3, -7, 6, 1])
print("Matriz de termos independentes: ", b)

# Resolvendo o sistema
x = np.linalg.solve(A, b)
print("Solução: ")
print("x =", x)

Matriz de coeficientes:  [[ 2  1 -1  1]
 [ 1 -3  2 -1]
 [ 4  1  1  2]
 [ 3 -2  1 -1]]
Matriz de termos independentes:  [ 3 -7  6  1]
Solução: 
x = [ 2.  6.  2. -5.]


In [46]:
print("2x + y - z + w = 3")
print("x - 3y + 2z - w = -7")
print("4x + y + z + 2w = 6")
print("3x - 2y + z - w = 1")
print("Solução:")
print("x:", round(x[0], 3))
print("y:", round(x[1], 3))
print("z:", round(x[2], 3))
print("w:", round(x[3], 3))

2x + y - z + w = 3
x - 3y + 2z - w = -7
4x + y + z + 2w = 6
3x - 2y + z - w = 1
Solução:
x: 2.0
y: 6.0
z: 2.0
w: -5.0


**Explicação:**

* **Criamos as matrizes:** Assim como no exemplo anterior, criamos a matriz de coeficientes `A` e o vetor de termos independentes `b`.
* **Resolvendo o sistema:** A função `np.linalg.solve(A, b)` resolve o sistema linear `Ax = b` e retorna o vetor solução `x`.

**Vantagens da função `np.linalg.solve`:**

* **Eficiência:** Utiliza algoritmos otimizados para resolver sistemas lineares.
* **Facilidade de uso:** A sintaxe é simples e intuitiva.
* **Versatilidade:** Pode lidar com sistemas de diferentes tamanhos e complexidades.

**Outras bibliotecas:**

Além do NumPy, outras bibliotecas como **SciPy** oferecem funcionalidades mais avançadas para álgebra linear, incluindo a resolução de sistemas lineares com diferentes métodos numéricos.

**Por que usar `np.linalg.solve`?**

* **Simplicidade:** Evita os cálculos complexos da Regra de Cramer.
* **Eficiência:** É mais rápido para sistemas maiores.
* **Robustez:** Lidar com diferentes tipos de sistemas lineares.

**Em resumo:**

Ao utilizar a função `np.linalg.solve` do NumPy, você simplifica significativamente a resolução de sistemas lineares em Python, tornando o seu código mais conciso e eficiente.